---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dtrcoke/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - /bin/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - /bin/php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - /bin/php composer-setup.php --filename=composer
    - /bin/php -r "unlink('composer-setup.php');"
    - /bin/php composer install
    - /bin/npm i && npm run build
    - /bin/php composer install --optimize-autoloader --no-dev
    - /bin/php artisan config:cache
    - /bin/php artisan event:cache
    - /bin/php artisan route:cache
    - /bin/php artisan view:cache